import { boolean, int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), username: varchar("username", { length: 64 }).unique(), passwordHash: text("passwordHash"), mustChangePassword: boolean("mustChangePassword").default(false).notNull(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export const rooms = mysqlTable("game_rooms", { id: int("id").autoincrement().primaryKey(), code: varchar("code", { length: 12 }).notNull().unique(), name: varchar("name", { length: 120 }).notNull(), status: mysqlEnum("status", ["open", "playing", "finished"]).default("open").notNull(), stateJson: text("stateJson"), createdBy: int("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const roomMembers = mysqlTable("game_room_members", { id: int("id").autoincrement().primaryKey(), roomId: int("roomId").notNull(), userId: int("userId").notNull(), joinedAt: timestamp("joinedAt").defaultNow().notNull(), lastSeenAt: timestamp("lastSeenAt").defaultNow().notNull() });
export const contacts = mysqlTable("game_contacts", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), contactUserId: int("contactUserId").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const scores = mysqlTable("game_scores", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), playerName: varchar("playerName", { length: 120 }).notNull(), points: int("points").notNull(), turns: int("turns").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert;
